### ISSUE TITLE
freecube_AWS01F pinout image broken link

### ISSUE THREAD

**Issue by jdavis7765** [blakadder/templates#1476]
https://cambridgeave.com/freecubepinout.jpg

**Comment by blakadder** [comment]
resolved

**Comment by N0ctrnl** [comment]
Don't suppose you still have this image do you? I'm doing some flashing on old devices and could really use it. Thanks!
